services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: vendinha_db
    ports:
      - "3306:3306"
    networks:
      - frontend-network
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: vendinha
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    networks:
      - frontend-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:8181
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge

volumes:
  db_data: